import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// NOTE: 클라이언트 컴포넌트로 사용 불가능
export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  analytics: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <p>RootLayout</p>
        <div>modal {modal}</div>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
